services:
  - type: web
    name: money-manager-backend
    env: node
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: PORT
        value: 10000
      - key: MONGO_URI
        value: mongodb+srv://abdur:abdur123@money.utbxxxb.mongodb.net/?appName=money-manager&retryWrites=true&w=majority
      - key: JWT_SECRET
        value: guvi_hackathon_secret_key_2026
      - key: NODE_ENV
        value: production